apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gitops-tw
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        albIngress: true
